### ISSUE TITLE
pdf是不是没法下载了。。

### ISSUE THREAD

**Issue by LiangJue** [yqylh/-Reptile#3]
https://cmpebooks.s3.cn-north-1.amazonaws.com.cn/books/5/978-7-111-52481-6_1-1/PDF/978-7-111-52481-6_1-1_2.pdf

**Comment by LiangJue** [comment]
还有个问题。现在是不是都没法下载了。（我想下经济方面的书。）感谢。

**Comment by yqylh** [comment]
是的，因为网站说
“武汉加油！中国加油！各位读者，非常抱歉，因工程技术图书馆免费开放阅读后访问量过大，服务器超载，暂不能提供服务。现正在紧急升级扩容中。感谢大家的支持，扩容完毕即恢复开放，请各位读者谅解。”
所以现在GG了，等到网站恢复了应该就可以的。
顺便我也想下经济学的书2333，等到网站恢复了我去把经济学的都下下来，现在有急需可以百度云

**Comment by LiangJue** [comment]
太感谢了。（还有管理。如果可以顺便也下一下。。）
（最后一个问题。因为我最近想学日语。然后北外网课课程都免费了。https://www.beiwaiclass.com/
就有没有办法可以把课程的视频都下载下来。有时间的话可以教教我吗。没有时间就算了。感谢！）

**Comment by yqylh** [comment]
ok，等网站恢复吧。
北外的话，本来写了个暴力，领取了所有课程（课程有效期很久，其实可以在线学）。后来发现这个网站有bug，我的课程太多了以后就会崩溃。
我刚写了一个脚本可以下北外单个课程下的所有视频，但是需要手动找一个url才行（我暂时没发现规律。

**Comment by yqylh** [comment]
https://github.com/yqylh/beiwaiclassDownloader
脚本在这里，需要自己去查一个变量的值就可以把这一门课的视频都下载下来，其实很方便（（（

**Comment by LiangJue** [comment]
感谢！
