### ISSUE TITLE
H5 书籍的 html 文件

### ISSUE THREAD

**Issue by lancelot96** [yqylh/-Reptile#4]
网盘里已经是转好的 pdf 文件，但是 pdf 在移动设备上阅读体验不是很好，所以想知道获取的 html 文件是否还在，或许可以生成 epub 格式的书籍，方便阅读

**Comment by yqylh** [comment]
库里面有html.7z，是html的文件合集，网上有htmltoepub的图书，但由于我家里网实在是太差了，所以我就不做这个转换了

**Comment by yqylh** [comment]
html里面的图片都是网站的直链，所以转换的话需要占用网速下载大量的图片

**Comment by lancelot96** [comment]
好的
