### ISSUE TITLE
can u help

### ISSUE THREAD

**Issue by blackrq** [yqylh/-Reptile#5]
作者你好
我需要的书不是计算机方面的，而且是非PDF版的，由于0编程基础，所以一直没搞懂这类代码。
能否帮忙代下载2本书，愿意支付书本实际标价。
版权问题由本人负责
盼回复
ISBN如下：
978-7-111-49888-9
978-7-111-51258-5

**Comment by yqylh** [comment]
你好，这两本书在网站可以直接下载pdf的版本，这代表着网站也没有非pdf版本，所以我也没办法qnq

**Comment by blackrq** [comment]
可能是我的表达有误，我并不需要非PDF版本，也不是用来编辑的。
我指的“非PDF版”是H5的意思，就是只能“在线阅读”，不能转换成PDF各式。
但是你说“这两本书在网站可以直接下载pdf的版本”，怎么下？

**Comment by yqylh** [comment]
http://ebooks.cmanuf.com/detail?id=9824
http://ebooks.cmanuf.com/detail?id=9150
进去点在线阅读确实可以直接下pdf

**Comment by Groot-lover** [comment]
understand




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"blackrq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 晚上6:19
收件人:&nbsp;"yqylh/-Reptile"<-Reptile@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [yqylh/-Reptile] can u help (#5)




Closed #5.

**Comment by Groot-lover** [comment]
i'm so sorry for the wrong message




------------------ 原始邮件 ------------------
发件人:&nbsp;"blackrq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 晚上6:19
收件人:&nbsp;"yqylh/-Reptile"<-Reptile@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [yqylh/-Reptile] can u help (#5)




Closed #5.
